# Generated by Django 5.1.4 on 2025-01-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
